database_url = "dev/dev.db"
addr_listen = "127.0.0.1:3030"

static_dir = "dev/static/"
image_dir = "img/"
avatar_dir = "avatar/"

static_url = "static"

avatar_width = 640
avatar_mini_width = 64
avatar_quality = 80

jwt_secret = "dev_secret"

jwt_refresh_exp_days = 30
jwt_access_exp_minutes = 30